from . import patient
from . import doctor_availability
from . import doctor
from . import dr_specialty
from . import disease
from . import department
from . import res_partner
from . import blood_donor
from . import blood_bank
from . import appointment